# docker container run -d -p 3838:3838 -v shiny-db:/srv/shiny-server --name yaptm yaptm

version: '3'

services:
  yaptm:
    image: yaptm
    ports:
      - '3838:3838' 
    volumes:
      - shiny-db:/srv/shiny-server

volumes:
  shiny-db: